### ISSUE TITLE
Need a CI

### ISSUE THREAD

**Issue by florent1933** [Atilla-Learn/portal#1]

**Comment by Thooms** [comment]
@aubincleme so based on our discussion, let's have a jenkins CI for this one. Would suit you if I scripted the whole build and you'd just have to scp/untar a `portal-web.tar.gz` on the right location?

**Comment by MrChoclate** [comment]
If Jenkins is up, I can configure Jenkins. Deploy script is always better !

**Comment by Thooms** [comment]
37a77a0 sooooooorry forgot to branch :D (but basically it follow the README and tar in the end).

**Comment by Thooms** [comment]
@aubincleme @MrChoclate for the Jenkins: just run the script and scp the resulting `.tar.gz` on webstatic. I included SHA1 in the archive name if we want to have a backup there.

**Comment by AntoineGirard** [comment]
It's works !
