### ISSUE TITLE
Integrate AMP HTML

### ISSUE THREAD

**Issue by florent1933** [Atilla-Learn/portal#29]
For a fast rendering of pages: https://github.com/ampproject/amphtml

**Comment by Thooms** [comment]
Useless according to me.

**Comment by florent1933** [comment]
It can help for SEO. For a future release and for a member who wants to try
this techno. It's not a critical issue

**Comment by MrChoclate** [comment]
- We do not need it.
- It seems to me that AMP HTML is not a super set of HTML, so it is hard to maintain without knowing AMP.

> Replace HTML5 elements that are not directly permitted in the specification such as amp-img and amp-video.

IMO it is better to start a new project to try this.

**Comment by florent1933** [comment]
This is an enhancement. So, we don't need enhancement? (Better SEO, better
UX). Add to a milestone instead of close?

Why hard to maintain? It's like everything...
- our css Framework is hard to maintain without knowing Materialize
- html is hard to maintain without knowing html
