### ISSUE TITLE
Add Django training

### ISSUE THREAD

**Issue by AntoineGirard** [Atilla-Learn/portal#38]
Hi @florent1933 

Could you add Dango training please ?

Thanks in advance,

**Comment by AntoineGirard** [comment]
ping @florent1933

**Comment by AntoineGirard** [comment]
ping @florent1933

**Comment by florent1933** [comment]
Someone stole my computer, so I don't have the video but I can put slides
and code.

**Comment by Alterrien** [comment]
Yes, I think that putting the slides and code would still be nice !

**Comment by Wonskcalb** [comment]
The video were not backed up somewhere else ?

**Comment by florent1933** [comment]
@Kirogo 👍 
@Wonscalb : Nope 

Slides : http://docdro.id/YwIuzxs
The repo is already on github: https://github.com/Atilla-Learn/django-2015

Someone can put it in the portal?

**Comment by Wonskcalb** [comment]
I'm going to check that toning, if I have time aside the upcoming talk. Can I have links some links to add to the portal?

**Comment by florent1933** [comment]
Thanks :) https://www.djangoproject.com/

**Comment by Wonskcalb** [comment]
Only this one? No direct links to some tutorial, or doc?

**Comment by florent1933** [comment]
Nope

**Comment by Wonskcalb** [comment]
Ok fine
