### ISSUE TITLE
Slides not available online

### ISSUE THREAD

**Issue by Wonskcalb** [Atilla-Learn/portal#51]
I think all the slides should be online, along with the git associated to it. Moverover, we should gather all those slides onto the very same server, in Atilla's infrastructure. Thooms slides for example are on it's server that is somewhat working through caches, as it's server is non-functionnal at this time of speaking

**Comment by florent1933** [comment]
I think, we should have a generator of presentation to uniformise all the content.

Why not use a generator like [yeoman](http://yeoman.io)

Each presentation will be in a git repo.

**Comment by Thooms** [comment]
No way I'm using this crap. But I admit we should have a single source of content for slides and such, thus I'll mail you all my slides @Wonscalb, and we can at least have a static server for this things (which is already the case I believe).

**Comment by florent1933** [comment]
@Thooms 😟

**Comment by Wonskcalb** [comment]
Yes indeed @Thooms I'll have to ask for the access though
@florent1933 I don't see how a generator can help us.

**Comment by Thooms** [comment]
Guys please do not use slack language on a public repository :)

**Comment by Wonscalb** [comment]
What are you talking about :D

**Comment by MrChoclate** [comment]
>  @florent1933 I don't see how a generator can help us.

The point of using yeoman would be to enforce us to follow specific (but undefined yet) convention like having the .yml content in the repo hosting the slides or using revealjs to make the slides.

IMO a Makefile producing the pdf in each repository should be ok

**Comment by Alterrien** [comment]
I'm up for centralizing all the slides on one single place, and a static server would be a great place for that, I think. The sources is another point worth to talk about, should we store them on the same place, or let them on the author's github/gitlab page ?

**Comment by Wonskcalb** [comment]
Hey, I'm just saying the system should require the slides to be directly visible. That's it! We could force ourselves to use something particular, but there is no need right now for this.

**Comment by Wonskcalb** [comment]
@Kirogo Two sides of a coin here : He's the author, he should be able to do so. But ifever his repo goes offline/deleted or something, that's not going to work. I'd go for everything on this repo, at least for some mirroring

**Comment by Alterrien** [comment]
After talking about it recently, we came to the conclusion that the slide's binaries will be made available on slides.atilla.org, and we will probably have a repo on ATILLA's gitlab synced with the aforementionned CDN.
Regarding the sources, it is at the author's discretion ; he/she can provide the sources or not, and he/she can host them where he/she wants. It would just be nice for the author to warn if he/she decides to not make the sources available online anymore, so we can update the talk's page and remove the source link.
