### ISSUE TITLE
Reduce thumbnails DPI

### ISSUE THREAD

**Issue by aubincleme** [Atilla-Learn/portal#59]
Especially on this page : https://learn.atilla.org/talks.html, about 8 thumbnails are loaded, each having a 1920x1080 pixels resolution. Each image then weights about 1.2 to 1.5M, which is quite a lot considering the fact that those images are just thumbnails.

This page weights then about 10M, and can degrade the browsing experience of a user far away from our servers (eg : in America) ; moreover, some people may sill have a low-data phone plan, and a 10M page could drastically reduce the amount of remaining data.

TO DO (proposed) : 
- Reduce the size of each thumbnail to a more "web compliant" resolution (eg : 854×480 pixels ; https://upload.wikimedia.org/wikipedia/commons/e/e5/Vector_Video_Standards2.svg).
- If the full-resolution image is still needed somewhere else, upload separate thumbnails.

**Comment by Alterrien** [comment]
I'll look on what I can do.

**Comment by Wonskcalb** [comment]
We might want to check that it still renders nice with high-resolution devices. I can produce images scaled down to what @aubincleme proposed

**Comment by Alterrien** [comment]
I can generate smaller resolution images, and I do not think that the higher-res images are used someplace else, so we might replace them entirely, what do you think ?

**Comment by Wonskcalb** [comment]
I agree, this is the only place where they're used. Entire replacement is the way to go. But we gotta be careful with "Retina" devices, which they all pretty much are on the day of writing this. As pointed on [this website](http://ivomynttinen.com/blog/a-guide-for-creating-a-better-retina-web), we should use generate media-queries to grab the correct 1x or 2x image, as for now, images-set [are only suppported ](caniuse.com/#feat=css-image-set)in webkit based browser

**Comment by Wonscalb** [comment]
As pointed on this [website](http://ivomynttinen.com/blog/a-guide-for-creating-a-better-retina-web), we should use generate media-queries to grab the correct 1x or 2x image, as for now, images-set [are only suppported](http://ivomynttinen.com/blog/a-guide-for-creating-a-better-retina-web) in webkit based browser

**Comment by Alterrien** [comment]
I think this is getting out of the issue's scope, as the goal here is to make the page load faster by having smaller images, and the cards on which the images are displayed have a fixed size, so the image will always roughly be displayed on a 400x200 resolution (correct me if I'm wrong).
Anyway, I'm finishing resizing the images and I'll open a PR so people can try on different screen sizes and tell me if it looks great.

**Comment by Wonskcalb** [comment]
Indeed. I'll probably end up opening an issue asking for high-density pictures
