### ISSUE TITLE
Add partner logo

### ISSUE THREAD

**Issue by AntoineGirard** [Atilla-Learn/portal#6]
Add EISTI logo on footer in a new "partners" category

**Comment by Thooms** [comment]
@neeev do we really need that? What do you mean by "partners category"?

**Comment by AntoineGirard** [comment]
Like this
![screen](https://cloud.githubusercontent.com/assets/12141434/11352155/057dfaa0-923b-11e5-91f8-b7a10a07864a.png)

**Comment by Thooms** [comment]
Ok. Now why would we want to do that?

**Comment by florent1933** [comment]
We have only one partner: EISTI. Others are bullshit!

**Comment by AntoineGirard** [comment]
@florent1933 Yes just EISTI logo.
@Thooms Because we used the EISTI premises.

**Comment by florent1933** [comment]
We can put the logo in the sidebar

**Comment by AntoineGirard** [comment]
@florent1933 :+1:

**Comment by Thooms** [comment]
@florent1933 can you handle it?

**Comment by florent1933** [comment]
I will do it

**Comment by florent1933** [comment]
Too hard for me.

@neeev

**Comment by neeev** [comment]
Solve #20
