### ISSUE TITLE
Source for django training are the material for the training, and not the sources of the slides

### ISSUE THREAD

**Issue by Alterrien** [Atilla-Learn/portal#61]
I think I let it slip when it went online yesterday, but it would be better to link on the training material as a link on the "A voir" section than as sources for the slides, since it is not the case.

**Comment by Wonskcalb** [comment]
That is what I've been told to do by @florent1933 on issue #38

**Comment by Alterrien** [comment]
Yes, the link for the slides' sources do not contain the sources. I am preparing a PR fixing this.
