### ISSUE TITLE
Migrate project to gitlab.atilla.org

### ISSUE THREAD

**Issue by aubincleme** [Atilla-Learn/portal#71]
We now have a super open source platform for hosting our projects : gitlab.atilla.org
Thereby, we should migrate this project to a new repository on gitlab.atilla.org and configure the GH repo to be a simple mirror.

Awaiting approval of @Kirogo for migration …

**Comment by Alterrien** [comment]
Good for me, I'll let you do it. I guess we're not keeping this repo up ?

**Comment by florent1933** [comment]
I can't log into gitlab.atilla.org... How can I contribute?

2016-11-27 17:02 GMT+01:00 Alexandre Terrien <notifications@github.com>:

**Comment by Wonskcalb** [comment]
You need to become a member of the association for this year

**Comment by florent1933** [comment]
So, I created the repo, maybe did 80% of the code and NOW I haven't access
to the repo.

Great ! Seems to be not very Open Source.

Congratulation

2016-11-27 23:37 GMT+01:00 Valentin Famelart <notifications@github.com>:

**Comment by Alterrien** [comment]
Wow hold on there, we don't need to get so rash towards each other. We had some privacy concerns (about putting some private info on this repo), so we'll separate the content and the code. The content will go to gitlab.atilla.org, and won't be mirrored. For the code, it'll be hosted on gitlab.atilla.org, development will take place there, but it'll be mirrored on github and we'll take code contribution from there too.

**Comment by aubincleme** [comment]
Closing as:
* The repo has been successfully moved to https://gitlab.atilla.org/atilla/learn-portal months ago
* Mirroring is done on GitHub
* The issue has not been updated since more than one year
