### ISSUE TITLE
need open graph tag

### ISSUE THREAD

**Issue by florent1933** [Atilla-Learn/portal#8]

**Comment by florent1933** [comment]
Facebook Platform
From Wikipedia, the free encyclopedia
The Facebook Platform is an umbrella term used to describe the set of services, tools, and products provided by the social networking service Facebook for third-party developers to create their own applications and services that access data in Facebook.[1] It was launched in 2010.[2] The platform offers a set of programming interfaces and tools which enable developers to integrate with the open "social graph" of personal relations and other things like songs, places, and Facebook pages. Applications on facebook.com, external websites, and devices are all allowed to access the graph.

Contents  [hide] 
1	History
2	High-level Platform components
2.1	Graph API
2.2	Authentication
2.3	Social plugins
2.4	Open Graph protocol
2.5	Iframes
2.6	Facebook Connect
2.7	Microformats
2.8	Mobile platform
3	Reception
4	See also
5	References
6	External links
History[edit]
Facebook launched the Facebook Platform on May 24, 2007, providing a framework for software developers to create applications that interact with core Facebook features.[1][2] A markup language called Facebook Markup Language was introduced simultaneously; it is used to customize the "look and feel" of applications that developers create. Using the Platform, Facebook launched several new applications,[1][2] including Gifts, allowing users to send virtual gifts to each other, Marketplace, allowing users to post free classified ads, Events, giving users a method of informing their friends about upcoming events, Video, letting users share homemade videos with one another,[3][4] and social network game, where users can use their connections to friends to help them advance in games they are playing. Many of the popular early social network games would combine capabilities, for instance, one of the early games to reach the top application spot, (Lil) Green Patch, combined virtual Gifts with Event notifications to friends and contributions to charities through Causes.

Third party companies provide application metrics, and several blogs arose in response to the clamor for Facebook applications. On July 4, 2007, Altura Ventures announced the "Altura 1 Facebook Investment Fund," becoming the world's first Facebook-only venture capital firm.[5]

On August 29, 2007, Facebook changed the way in which the popularity of applications is measured, to give attention to the more engaging applications, following criticism that ranking applications only by the number of people who had installed the application was giving an advantage to the highly viral, yet useless applications.[6] Tech blog Valleywag has criticized Facebook Applications, labeling them a "cornucopia of uselessness."[7] Others have called for limiting third-party applications so the Facebook user experience is not degraded.[8][9]

Applications that have been created on the Platform include chess, which both allow users to play games with their friends.[10] In such games, a user's moves are saved on the website, allowing the next move to be made at any time rather than immediately after the previous move.[11]

By November 3, 2007, seven thousand applications had been developed on the Facebook Platform, with another hundred created every day.[12] By the second annual f8 developers conference on July 23, 2008, the number of applications had grown to 33,000,[13] and the number of registered developers had exceeded 400,000.[14]

Within a few months of launching the Facebook Platform, issues arose regarding "application spam", which involves Facebook applications "spamming" users to request it be installed.[15]

Facebook integration was announced for the Xbox 360 and Nintendo DSi on June 1, 2009 at E3.[16] On November 18, 2009, Sony announced an integration with Facebook to deliver the first phase of a variety of new features to further connect and enhance the online social experiences of PlayStation 3.[17] On February 2, 2010, Facebook announced the release of HipHop for PHP as an opensource project.[18] Mark Zuckerberg said that his team from Facebook is developing a Facebook search engine.[19] “Facebook is pretty well placed to respond to people’s questions. At some point, we will. We have a team that is working on it", said Mark Zuckerberg. For him, the traditional search engines return too many results that do not necessarily respond to questions. “The search engines really need to evolve a set of answers: 'I have a specific question, answer this question for me.'"

On June 10, 2014, Facebook announced Haxl, a Haskell library that simplified the access to remote data, such as databases or web-based services.[20]

High-level Platform components[edit]
Graph API[edit]
The Graph API is the core of Facebook Platform, enabling developers to read from and write data into Facebook. The Graph API presents a simple, consistent view of the Facebook social graph, uniformly representing objects in the graph (e.g., people, photos, events, and pages) and the connections between them (e.g., friend relationships, shared content, and photo tags).[21]

Authentication[edit]
Facebook authentication enables developers’ applications to interact with the Graph API on behalf of Facebook users, and it provides a single-sign on mechanism across web, mobile, and desktop apps.[22]

Social plugins[edit]
Social plugins – including the Like Button, Recommendations, and Activity Feed – enable developers to provide social experiences to their users with just a few lines of HTML. All social plugins are extensions of Facebook and are specifically designed so no user data is shared with the sites on which they appear.[23]

Open Graph protocol[edit]

Open Graph protocol logo
The Open Graph protocol enables developers to integrate their pages into the social graph. These pages gain the functionality of other graph objects including profile links and stream updates for connected users.[24] As an example, the following is the Open Graph protocol markup for text on Software Master Center:[25]

<meta property="og:title" content="text - Easily enter international characters in Internet Explorer." />
<meta property="og:type" content="product" />
<meta property="og:url" content="http://www.softwaremastercenter.com/text_20605-1_software.html" />
<meta property="og:image" content="http://regnow.img.digitalriver.com/vendor/20605/Boxshot1.jpg" />
<meta property="og:site_name" content="Software Master Center" />
<meta property="og:description" content="Easily enter international/foreign characters in Internet Explorer." />
Iframes[edit]
Facebook uses iframes to allow third-party developers to create applications that are hosted separately from Facebook, but operate within a Facebook session and are accessed through a user's profile. Since iframes essentially nest independent websites within a Facebook session, their content is distinct from Facebook formatting.

Before iframes, Facebook used 'Facebook Markup Language (FBML)' to allow Facebook Application developers to customize the "look and feel" of their applications, to a limited extent. FBML is a specification of how to encode content so that Facebook's servers can read and publish it, which is needed in the Facebook-specific feed so that Facebook's system can properly parse content and publish it as specified.[26] FBML set by any application is cached by Facebook until a subsequent API call replaces it. Facebook also offers a specialized Facebook JavaScript (FBJS) library.[27]

Facebook stopped accepting new FBML applications on March 18, 2011,[28] but continued to support existing FBML tabs and applications. Since January 1, 2012 FBML was no longer supported, and FBML no longer functioned as of June 1, 2012.[citation needed]

Facebook Connect[edit]
Facebook Connect,[29] also called Log in with Facebook, like OpenID, is a set of authentication APIs from Facebook that developers can use to help their users connect and share with such users' Facebook friends (on and off Facebook) and increase engagement for their website or application. When so used, Facebook members can log on to third-party websites, applications, mobile devices and gaming systems with their Facebook identity and, while logged in, can connect with friends via these media and post information and updates to their Facebook profile.

Originally unveiled during Facebook’s developer conference, F8, in July 2008, Log in with Facebook became generally available in December 2008. According to an article from The New York Times, "Some say the services are representative of surprising new thinking in Silicon Valley. Instead of trying to hoard information about their users, the Internet companies (including Facebook, Google, MySpace and Twitter) all share at least some of that data so people do not have to enter the same identifying information again and again on different sites."[30]

Log in with Facebook cannot be used by users in locations that cannot access Facebook (e.g. China), even if the third-party site is otherwise accessible from that location.[31]

According to Facebook, users who logged in to The Huffington Post with Facebook spent more time on the site than the average user.[32]

Microformats[edit]
In February 2011, Facebook began to use the hCalendar microformat to mark up events, and the hCard for the events' venues, enabling the extraction of details to users' own calendar or mapping applications.[33]

Mobile platform[edit]
The UI framework for the mobile website is based on Xhp, the Javelin Javascript library, and WURFL.[34] The mobile platform has grown dramatically in popularity since its launch. In December 2012, the number of users signing into the site from mobile devices exceeded web-based logins for the first time.[35]

Reception[edit]
[icon]	This section requires expansion. (April 2013)
The Guardian expressed concerns that users publishing content through a third party provider are exposed to losing their web positioning if their service is removed; and the open graph could force connecting web presence to Facebook social services even for people using their own publishing channels.[36]

Primarily attempting to create viral applications is a method that has certainly been employed by numerous Facebook application developers. Stanford University even offered a class in the Fall of 2007, entitled, Computer Science (CS) 377W: "Create Engaging Web Applications Using Metrics and Learning on Facebook". Numerous applications created by the class were highly successful, and ranked amongst the top Facebook applications, with some achieving over 3.5 million users in a month.[37]

See also[edit]
Facebook features
Facebook PMD Center
References[edit]
^ Jump up to: a b c Kirkpatrick, David (2007-05-29). "Facebook's plan to hook up the world". CNN. Retrieved 2008-03-05.
^ Jump up to: a b c "How To: Get Started with the Open Graph". Facebook. 2011-09-23.
Jump up ^ George-Cosh, David (2007-07-05). "Facebook users embracing the Marketplace". The Globe and Mail (Toronto). Retrieved 2008-05-03.
Jump up ^ Schwankert, Steven (2007-05-25). "Facebook Launches Video System". PC World. Retrieved 2008-05-03.
Jump up ^ "Altura Ventures news". Altura Ventures. 2007-07-04. Retrieved 2007-09-03.
Jump up ^ Morin, Dave (2007-08-29). "A shift to engagement". Facebook. Retrieved 2007-08-31.
Jump up ^ "Can a Facebook app possibly be useful?". Valleywag.com. 2005-09-26. Archived from the original on 2013-06-13. Retrieved 2007-10-16.
Jump up ^ Timmons, Zack (2007-12-03). "Useless applications plague Facebook". The Lantern. Retrieved 2008-03-05.
Jump up ^ Lee, Tim (2007-11-30). "Irritating Your Customers Is Almost Never A Good Business Strategy". Retrieved 2008-03-05.
Jump up ^ "Chess". Facebook. Retrieved 2008-03-15.
Jump up ^ Kim, Ryan (2007-11-20). "Mountain View startup Meebo aims to revolutionize instant messaging". San Francisco Chronicle. Retrieved 2008-03-15.
Jump up ^ Rampell, Catherine (2007-11-03). "Widgets Become Coins of the Social Realm". The Washington Post. p. D01. Retrieved 2008-05-07.
Jump up ^ Ustinova, Anastasia (2008-07-23). "Developers compete at Facebook conference". San Francisco Chronicle. Retrieved 2008-08-14.
Jump up ^ "Facebook Expands Power of Platform Across the Web and Around the World". Facebook. 2008-07-23. Retrieved 2008-08-14.
Jump up ^ "Facebook cracks down on developer spam". The Washington Post. Retrieved 2008-03-15.
Jump up ^ "Microsoft E3 Announcement". Neelscompany.com. 2015-02-08.
Jump up ^ "Sony to Offer Richer Online Social Experience to PS3 Owners With Facebook Integration". ign.com. 2009-11-18. Retrieved 2010-05-06.
Jump up ^ Kincaid, Jason. "Live From Facebook's HipHop Technology Tasting". techcrunch.com. © 2010 TechCrunch. Retrieved 6 July 2010.
Jump up ^ Facebook is developing its own Search Engine. Search for technology (2012-09-17). Retrieved on 2013-07-24.
Jump up ^ "Open-sourcing Haxl, a library for Haskell". Facebook Code. Retrieved 2014-06-10.
Jump up ^ "Graph API".
Jump up ^ "Authentication".
Jump up ^ "Social Plugins".
Jump up ^ "Open Graph Protocol".
Jump up ^ Software Master Center. "text - International On-Screen text for Internet Explorer". Retrieved 13 July 2011.
Jump up ^ "Facebook Markup Language - A "Reverse API"" (Press release). Mashery. 2007-05-26.
Jump up ^ "FBJS".
Jump up ^ Nikolay Valtchanov. "Platform Updates: Operation Developer Love". Retrieved 16 May 2011.
Jump up ^ "Announcing Facebook Connect". Facebook.com. 2008-05-09. Retrieved 2014-05-23.
Jump up ^ NY Times
Jump up ^ Chester, Ken (12 August 2013). "Censorship, external authentication, and other social media lessons from China’s Great Firewall". Tech in Asia. Retrieved 4 June 2015.
Jump up ^ Danny Sullivan (22 May 2011). "By The Numbers: How Facebook Says Likes & Social Plugins Help Websites". Search Engine Land.
Jump up ^ linski, Emil (2011-02-18). "Facebook adds and micro-formats to Events". ZDNet. Retrieved 24 March 2011.
Jump up ^ Ali, Khurram (May 21, 2011). "Facebook Mobile Website – Transition – Issues". techprolonged.com. Retrieved December 29, 2011. Facebook has mention in the note that the new website is powered by a UI framework based on XHP, Javelin and WURFL.
Jump up ^ Olanoff, Drew (Jan 30, 2013). "For The First Time, Facebook’s 680M Mobile MAUs Surpassed Desktop DAUs — Zuck Says It’s Now A "Mobile Company"". Techcrunch. Retrieved 28 May 2014.
Jump up ^ Adrian Short (2011-09-27). "Why Facebook's new Open Graph makes us all part of the web underclass". London: The Guardian.
Jump up ^ Kamil Dada (2007-11-30). "Kamil Dada from Stanford University explains the success of Facebook applications developed in a class at Stanford University". Archived from the original on January 18, 2008. Retrieved 2007-12-15.

**Comment by Thooms** [comment]
Fixed by #17
